# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773e8eeea66df1aaebf3a4bcf565aa234be513e7e47bce36bdc1a99c08f88bb8260d8ae6f78b3a41e4eae84b467636bb1baddab4920508ea860adcaf0137ec5d

test:
  secret_key_base: c1589437d9cf85aad822318c574a20f97da7cc24ea894332316fcfbdb16c4673946f69d362d0f45478734daa7536d217a8ba4b90e303756ecec9a194aaff5aa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
